version: '3.8'

services:
  db:
    #https://hub.docker.com/_/postgres
    #https://geshan.com.np/blog/2021/12/docker-postgres/
    image: postgres
    build: apps/pgdb
    container_name: pg_container
    
    restart: always

    environment:
      # "POSTGRES_USER" This variable will create the specified user with superuser power **and a database** with the same name. 
      # If it is not specified, then the default user of "postgres" will be used.
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      # "POSTGRES_DB" This optional environment variable can be used to define a different name for the default database 
      # that is created when the image is first started. If **it is not specified**, then the **value of POSTGRES_USER will be used**.
      # POSTGRES_DB: test_db
      DB_NAME: dwarehouse
      DB_GROUP_R: readers
      DB_GROUP_W: writers
      DB_GEN_USER_NAME: user1
      DB_GEN_USER_PASSWORD: user1
      DB_HOST: 172.22.0.2
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/tmp/sql_script
      - ./sql/initdb:/docker-entrypoint-initdb.d
      # ask docker-compose to manage the volume in a name called "db" which is further added to be a local driver:
      - pg_data:/var/lib/postgresql/data
    networks:
      inyova-static:
        ipv4_address: 172.22.0.2

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      inyova-static:
        ipv4_address: 172.22.0.3
# https://towardsdatascience.com/how-to-run-postgresql-and-pgadmin-using-docker-3a6a8ae918b5
#

networks:
  inyova-static:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.1.0/16

volumes:
  pg_data:
    driver: local
