version: '3.8'

services:
  db:
    image: postgres
    build: apps/pgdb
    container_name: pg_container
    
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PROJECT_DATABASE: dwarehouse
      PROJECT_USERGROUP: writers
      DB_USER_NAME: user1
      DB_USER_PASSWORD: user1
    ports:
      - "5432:5432"
    volumes:
      - ./sql_script:/tmp/sql_script
      # ask docker-compose to manage the volume in a name called "db" which is further added to be a local driver:
      - db:/var/lib/postgresql/data
    networks:
      - apps
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - apps
  # web:
  #   #restart: always
  #   image: python:3.9-alpine
  #   ports:
  #     - "5051:80"
  #   volumes:
  #     - .:/tmp/app
  #   depends_on:
  #     - db
  #   #command: 
# https://towardsdatascience.com/how-to-run-postgresql-and-pgadmin-using-docker-3a6a8ae918b5
#

networks:
  apps:
    driver: bridge

volumes:
  db:
    driver: local